version: '2'
services:
    titanium-app:
        image: titanium
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://titanium-mysql:3306/titanium?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    titanium-mysql:
        extends:
            file: mysql.yml
            service: titanium-mysql
